name: create a branch jobs in dev environment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
      environment:
        description: 'Bundle target to run the workflow on'
        required: true
        default: 'develop'
defaults:
    run:
       working-directory: oamlops
env:
    DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN_PRD }}
    DATABRICKS_BUNDLE_ENV: ${{ github.event.inputs.environment }}
    BRANCH_NAME: ${{ github.event.inputs.branch }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: test environment 
      run: | 
        echo "DATABRICKS_BUNDLE_ENV  ${{ env.DATABRICKS_BUNDLE_ENV }} "
        echo "BRANCH_NAME  ${{ env.BRANCH_NAME }} "
    
    - name: Install specific version of Databricks CLI
      run: |
               pwd
               ls -lrt databricks_cli_0.220.0_linux/databricks
               whoami
               chmod 777 databricks_cli_0.220.0_linux/databricks
               databricks_cli_0.220.0_linux/databricks -v
               cp databricks_cli_0.220.0_linux/databricks .
               ./databricks -v
    - name: Validation
      run: ./databricks bundle validate #--output json
    - name: deploy
      run: ./databricks bundle deploy --var="git_branch=${{ env.BRANCH_NAME }},git_url=${{ github.server_url }}/${{ github.repository }}.git"
