name: delete a brunch jobs in dev environment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
defaults:
    run:
       working-directory: oamlops
env:
    #DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN_QA }}
    DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN_PRD }}
    DATABRICKS_BUNDLE_ENV: dev
    BRANCH_NAME: ${{ github.event.inputs.branch }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: test environment 
      run: | 
        echo "DATABRICKS_BUNDLE_ENV  ${{ env.DATABRICKS_BUNDLE_ENV }} "
        echo "BRANCH_NAME  ${{ env.BRANCH_NAME }} "
    
    - name: Install specific version of Databricks CLI
      run: |
               pwd
               ls -lrt databricks_cli_0.220.0_linux/databricks
               whoami
               chmod 777 databricks_cli_0.220.0_linux/databricks
               databricks_cli_0.220.0_linux/databricks -v
               cp databricks_cli_0.220.0_linux/databricks .
               ./databricks -v
 #       # Download the Databricks CLI.
 #       - name: Install Databricks CLI
 #         run: |
 #            curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
 #            databricks -v
      # Deploy the bundle to the "qa" target as defined
      # in the bundle's settings file.
    - name: Validation
      run: ./databricks bundle validate 
    - name: deploy
      run: ./databricks bundle destroy --auto-approve --var="git_branch=${{ env.BRANCH_NAME }},git_url=${{ github.server_url }}/${{ github.repository }}.git"
